### ISSUE TITLE
[feature] Github Action을 통한 자동 배포

### ISSUE THREAD

**Issue by jungdaesuh** [dnwlsrla40/heart-muscle#40]
### 추가/개선 필요 요소
- [ ] feature : Github Action을 통한 자동 배포, CI/CD 구현

**Comment by dnwlsrla40** [comment]
배포 후 관리를 위한 툴로 AWS Elastic Beanstalk를 사용했을 때의 장점

- 완전 관리형이기 때문에 초반 세팅만 잘 해준다면 이후 추가적으로 손 댈 부분이 적다.
- 자동으로 환경을 만들어준다. 그러므로 개발자가 직접 알아야 하는 프로세스가 적다.
- Load Balancer, Auto Scaling, Health Checker 등 배포 이후에 운영을 하면서 필요한 것들을 쉽게 수정 및 조작할 수 있다.
- 다양한 배포 방식을 제공한다.(Rolling, Canary, Immutable, Blue-green 등등)
- Customizing이 생각보다 어렵지 않다.
- 버전 관리가 자동으로 잘 되고 있으며, 이로 인해 이전 버전을 재배포하기도 쉽다.
