### ISSUE TITLE
[보안] : 몽고db환경변수 설정하기

### ISSUE THREAD

**Issue by JungDaeSuh** [dnwlsrla40/heart-muscle#41]
### 추가/개선 필요 요소
 - 몽고db 환경변수 설정하기
 
### 상세 요구 사항
- "데이터 베이스의 중요정보를 서버의 환경변수에 저장해서 파이썬에서 서버의 환경변수 값을 읽는 방식을 추천드립니다."

### 링크
https://cat-minzzi.tistory.com/52

**Comment by jungdaesuh** [comment]
2차 프로젝트 마무리. 

모든 팀원이 환경변수 설정의 중요성에 대해서 인지.
